#!/bin/bash

FILE=./last_ip
IP=$(curl ipinfo.io/ip)

# Hosts in your domain provider, any subdomain should be also included.
HOSTS=('www' '*' '@')

function call_api {
    for host in "${HOSTS[@]}"
    do
            curl -s "https://dynamicdns.park-your-domain.com/update?domain=$DNS_DOMAIN_NAME&password=$DNS_PASSWORD&host=$host"
    done
}

if [ -f "$FILE" ]; then
    echo "reading last_ip..."
    LAST_IP=$( cat $FILE )
    echo "last ip: $LAST_IP"
    echo "current ip: $IP"
    if [ $IP != $LAST_IP ]; then
        echo "The ip is different"
        echo $IP > $FILE
	    call_api
    else
        echo "The ip is the same"
    fi
else 
    echo -e "$FILE does not exist.\nCreating file..."
    echo $IP > $FILE
    call_api
fi
